unify_backend:
    resource: "@UnifyBackendBundle/Resources/config/routing.yml"
    prefix:   /

unify_web:
    resource: "@UnifyWebBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
