<?php

namespace Unify\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getLatestProducts($limit){
        return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('p')
                ->from('UnifyWebBundle:Product', 'p')
                ->where('p.img is not null')
                ->orderBy('p.created_at', 'desc')
                ->getQuery()
                ->setMaxResults($limit)
                ->getResult();
    }
}
