parameters:
#    unify_web.example.class: Unify\WebBundle\Example

services:
#    unify_web.example:
#        class: %unify_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
